name: Sync Fork

on:
  schedule:
    - cron: '0 19 * * *'   # 每天 UTC 19:00 运行一次 (北京时间凌晨 3:00)
  workflow_dispatch:        # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/xintaikeji/MoonTV.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main || true

      - name: Push changes
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
